apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: golang-sbom-11724-gitops
  description: This is GitOps manifest for golang-sbom-11724   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: golang-sbom-11724
    janus-idp.io/tekton: golang-sbom-11724 
    backstage.io/kubernetes-id: golang-sbom-11724 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:golang-sbom-11724
