apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: golang-sbom-11724
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golang-sbom-11724 
  name: golang-sbom-11724
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: golang-sbom-11724
    weight: 100 
