apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: golang-sbom-11724
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golang-sbom-11724 
  name: golang-sbom-11724
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: golang-sbom-11724 
